[package]
name = "loom"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
default-run = "loomd"

[workspace]
members = ["crates/loom-dsp", "crates/loom-ipc", "crates/loom-pipewire"]
resolver = "3"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
tracing-subscriber = "0.3.23"
tracing = "0.1.44"
toml = "1.0"
serde = { version = "1.0", features = ["derive"] }
directories = "6.0.0"
palette = { version = "0.7.7", default-features = false, features = ["std"] }
loom-dsp = { path = "crates/loom-dsp" }
loom-pipewire = { path = "crates/loom-pipewire" }
loom-ipc = { path = "crates/loom-ipc" }
signal-hook = "0.3.18"
