[package]
name = "loom"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[workspace]
members = ["crates/loom-dsp", "crates/loom-ipc", "crates/loom-pipewire"]
resolver = "3"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
loom-dsp = { path = "crates/loom-dsp" }
loom-pipewire = { path = "crates/loom-pipewire" }
loom-ipc = { path = "crates/loom-ipc" }

[[bin]]
name = "daemon"
path = "src/bin/loomd/main.rs"

[[bin]]
name = "gui-client"
path = "src/bin/loomctl/main.rs"
